name: BKCommonLib
main: com.bergerkiller.bukkit.common.internal.CommonPlugin
version: ${project.version}
authors: [bergerkiller, lenis0012, timstans, bubba1234119, KamikazePlatypus, mg_1999, Friwi]
metrics: true
load: STARTUP
description: Is used in all of my plugins to re-use common functions
softdepend: [Vault, ProtocolLib]
dev-url: ${project.url}
commands:
  commondebug:
    description: Developer debugging commands for changing values
    aliases: [debug]
    usage: /debug [name] [value...]